---
apiVersion: v1
kind: Namespace
metadata:
  name: devoxx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devoxx-deployment
  labels:
    app: devoxx
  namespace: devoxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devoxx
  template:
    metadata:
      labels:
        app: devoxx
    spec:
      containers:
      - name: devoxx
        image: DEVOXX_IMG
        ports:
        - containerPort: 3000
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devoxx
  name: devoxx-service
  namespace: devoxx
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: devoxx
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
