---
apiVersion: v1
kind: Namespace
metadata:
  name: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
  namespace: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: hello:1.0.16
        ports:
        - containerPort: 3000
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello-service
  namespace: hello
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: hello
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
---
apiVersion: v1
kind: Service
metadata:
  name: devoxx-remote-service
  namespace: hello
spec:
  type: ExternalName
  externalName: devoxx-service.devoxx.svc.cluster.local
  ports:
  - port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: world-remote-service
  namespace: hello
spec:
  type: ExternalName
  externalName: world-service.devoxx.svc.cluster.local
  ports:
  - port: 3000

