---
apiVersion: v1
kind: Namespace
metadata:
  name: world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-deployment
  labels:
    app: world
  namespace: world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
      - name: world
        image: world:1.0.1
        ports:
        - containerPort: 3000
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: world
  name: world-service
  namespace: world
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 3001
    protocol: TCP
    targetPort: 3000
  selector:
    app: world
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
